services:
  - type: web
    name: autoprego
    runtime: python
    plan: free

    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn app:app"

    build:
      env:
        PYTHON_VERSION: 3.11.6
